### ISSUE TITLE
Fix strategy precedence when applied to `html`

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/tailwindcss-theming#11]
Currently, the `assignable` option makes the themes assignable (the manner depends on the choosen strategy), but the `:root` theme takes precedence if the strategy is applied to `html`. 

For instance, `<html data-theme="dark">` won't work because `:root` will take precedence. 

I didn't realize this before because I was used to apply the strategies on `body`. 

- The "workaround" is to not use the strategy on `html`, but on anything else.
- The fix is to modify the assignable themes' selectors.

**Comment by sibbngheid** [comment]
How this is fixed?

**Comment by innocenzi** [comment]
Hey, it's not. I figured that wasn't particularly important. Is it an issue for you?

**Comment by sibbngheid** [comment]
Yes. I manually fix on my machine by removing this line but i would prefer it to be officially supported.

https://github.com/innocenzi/tailwindcss-theming/blob/master/src/util/generateCssConfiguration.ts#L30

Providing option for disabling `:root` selection can be the first solution that comes to mind, but being able to define themes without calling them as _default_ would be better. In this case, this themes should only care theme strategy.

**Comment by innocenzi** [comment]
Well, you can use `addTheme` for it to not be a "default" theme, but if you don't have a default theme, the plugin will throw an error. 

I'll change that in the next version, it will only send a warning. You'll have to set the theme targetable and use a name on it, and it won't use `:root`. 

Will that solve your issue?

**Comment by sibbngheid** [comment]
Currently using my own theming plugin but this solution is what I tried while using this plugin and get error as you said.

**Comment by innocenzi** [comment]
Alright. That'll be fixed in the next version, then. 👍
