### ISSUE TITLE
Variables created but classes not generated when using Astro.

### ISSUE THREAD

**Issue by iivvaannxx** [innocenzi/tailwindcss-theming#59]
Hello!

I am implementing the traditional light/dark mode for a website I am building using [Astro.js](https://astro.build). Initially, I decided to go for the Tailwind way of adding the ```dark:``` prefix over each class, but recently I decided to switch to this plugin workflow as I find it quite more comfortable. 

The thing is, I am following the simple Quick Start but I don't see it working, and I don't know why. When using Astro, Tailwind works as an [integration](https://docs.astro.build/en/guides/integrations-guide/tailwind/) (as they call it) I suppose it could be something related to that.

This is my theme.config:
```js
const { ThemeManager, Theme } = require('tailwindcss-theming/api');

const light = new Theme();
light.setName('light');
light.targetable();
light.addColors({

    'primary': '#FFFFFF',
});


const dark = new Theme();
dark.setName('dark');
dark.targetable();
dark.addColors({

    'primary': '#000000',
});

const themeManager = new ThemeManager();
themeManager.setDefaultTheme(light);
themeManager.setDefaultDarkTheme(dark);

module.exports = themeManager;

```

Then I import it to the Tailwind config:
```js
'plugins': [

        require('tailwindcss-theming')({
        
	        themes: 'theme.config.cjs',
        }),
],
```

After that, I rebuild my project and test it, I add this `div` to the page on which I am testing the feature:
```html 
<div class = "h-screen bg-primary"></div>
```

But when I go to the corresponding page and try to manually update the theme via the DevTools (by adding the `data-theme` attribute) nothing happens. The variable is declared as you can see in the screenshot below, but it seems that the corresponding class `bg-primary` is not generated correctly (it doesn't even appear on the listed styles).

![image](https://user-images.githubusercontent.com/47715589/202910015-df7f8efa-8cc1-46f9-93e9-d909484771b3.png)

I apologize if I missed something on the configuration guide that could be causing this issue, but as I couldn't find why it happens or any kind of workaround, I thought to post this and see if anyone got the same issue or found a solution.

Thanks for the amazing work!

EDIT: I created an [example project](https://stackblitz.com/edit/tailwind-theming-plugin-astro?file=src/pages/index.astro) trying to set up this plugin with Astro. The exact same thing happens.

**Comment by innocenzi** [comment]
Hey, I'm sorry, this package is not maintained since Tailwind 1.2. Didn't archive in case someone want to contact me to take it over.

Consider using one of the alternatives in the readme. Adam will also be adding a new syntax for using CSS variables, so you might as well use that: https://twitter.com/adamwathan/status/1594004160659296256
